const column = [
    { label: "原系统ID", prop: "originalId", width: "120", editable: true, editType: 'text' },
    { label: "检测项目ID", prop: "testsId", width: "120", editable: true, editType: 'text' },
    { label: "执行标准ID", prop: "sampleProgramsId", width: "120", editable: true, editType: 'text' },
    { label: "项目ID", prop: "projectId", width: "120", editable: true, editType: 'text' },
    { label: "执行标准代码", prop: "spCode", width: "150", editable: true, editType: 'text' },
    { label: "方案测试名称", prop: "spTestName", width: "150", editable: true, editType: 'text' },
    { label: "测试名称", prop: "testName", width: "150", editable: true, editType: 'text' },
    { label: "测试别名", prop: "testAlias", width: "150", editable: true, editType: 'text' },
    { label: "特殊测试名称", prop: "specialTestName", width: "150", editable: true, editType: 'text' },
    { label: "测试分类ID", prop: "testCateId", width: "120", editable: true, editType: 'text' },
    { label: "测试类型", prop: "testType", width: "120", editable: true, editType: 'text' },
    { label: "方案类型", prop: "profileType", width: "120", editable: true, editType: 'text' },
    { label: "项目代码", prop: "programCode", width: "120", editable: true, editType: 'text' },
    { label: "数量", prop: "qty", width: "100", editable: true, editType: 'text' },
    { label: "数量单位", prop: "qtyUnits", width: "100", editable: true, editType: 'text' },
    { label: "价格", prop: "price", width: "100", editable: true, editType: 'text' },
    { label: "附加价格", prop: "addPrice", width: "100", editable: true, editType: 'text' },
    { label: "价格单位", prop: "priceUnits", width: "100", editable: true, editType: 'text' },
    { label: "标准", prop: "criterion", width: "150", editable: true, editType: 'textarea' },
    { label: "测试标准", prop: "testCriterion", width: "150", editable: true, editType: 'textarea' },
    { label: "评估规则", prop: "evaluateRule", width: "150", editable: true, editType: 'text' },
    { label: "COP编号", prop: "copNo", width: "120", editable: true, editType: 'text' },
    { label: "低限A", prop: "lowA", width: "100", editable: true, editType: 'text' },
    { label: "高限A", prop: "highA", width: "100", editable: true, editType: 'text' },
    { label: "高限单位", prop: "highAUnit", width: "100", editable: true, editType: 'text' },
    { label: "单位", prop: "units", width: "100", editable: true, editType: 'text' },
    { label: "文本限制", prop: "charLimits", width: "150", editable: true, editType: 'textarea' },
    { label: "数据参考", prop: "dataReference", width: "150", editable: true, editType: 'textarea' },
    { label: "状态", prop: "status", width: "100", editable: true, editType: 'text' },
    { label: "是否退休", prop: "isRetire", width: "100", editable: true, editType: 'text' },
    { label: "是否主项目", prop: "isMainPro", width: "100", editable: true, editType: 'text' },
    { label: "冻结标志", prop: "freezeFlag", width: "100", editable: true, editType: 'text' },
    { label: "默认测试", prop: "defaultTest", width: "100", editable: true, editType: 'text' },
    { label: "审核标志", prop: "auditFlag", width: "100", editable: true, editType: 'text' },
    { label: "审核级别", prop: "auditLevel", width: "100", editable: true, editType: 'text' },
    { label: "行审核", prop: "rowAudit", width: "100", editable: true, editType: 'text' },
    { label: "显示状态", prop: "dispStatus", width: "100", editable: true, editType: 'text' },
    { label: "报告类型", prop: "reportType", width: "100", editable: true, editType: 'text' },
    { label: "报告备注", prop: "reportRemark", width: "150", editable: true, editType: 'textarea' },
    { label: "抽样计划", prop: "drawPlan", width: "120", editable: true, editType: 'text' },
    { label: "部门", prop: "dept", width: "120", editable: true, editType: 'text' },
    { label: "成本中心ID", prop: "ccId", width: "120", editable: true, editType: 'text' },
    { label: "提交公司", prop: "submitCorp", width: "150", editable: true, editType: 'text' },
    { label: "特殊组名称", prop: "specialGroupName", width: "150", editable: true, editType: 'text' },
    { label: "主组汇总", prop: "mainGroupZum", width: "150", editable: true, editType: 'text' },
    { label: "组编号", prop: "groupNums", width: "120", editable: true, editType: 'text' },
    { label: "开始使用日期", prop: "startUseDate", width: "160", type: "date", editable: true, editType: 'date' },
    { label: "到期日期", prop: "expirationDate", width: "160", type: "date", editable: true, editType: 'date' },
    { label: "版本", prop: "version", width: "100", editable: true, editType: 'text' },
    { label: "方案描述", prop: "profile", width: "150", editable: true, editType: 'text' },
    { label: "说明描述", prop: "explainDesc", width: "150", editable: true, editType: 'textarea' },
    { label: "备注说明", prop: "comments", width: "150", editable: true, editType: 'textarea' },
    { label: "规格分析物备注", prop: "specAnalytesComments", width: "150", editable: true, editType: 'textarea' },
    { label: "工作流ID", prop: "workflowId", width: "120", editable: true, editType: 'text' },
    { label: "排序", prop: "sorter", width: "100", editable: true, editType: 'text' },
    { label: "记录者描述", prop: "recorderDesc", width: "150", editable: true, editType: 'textarea' },
    { label: "审核人代码", prop: "auditorCode", width: "120", editable: true, editType: 'text' },
    { label: "审核人描述", prop: "auditorDesc", width: "150", editable: true, editType: 'textarea' },
    { label: "审核时间", prop: "auditTime", width: "160", type: "date", editable: true, editType: 'date' },
    { label: "冻结人代码", prop: "freezerCode", width: "120", editable: true, editType: 'text' },
    { label: "冻结人描述", prop: "freezerDesc", width: "150", editable: true, editType: 'textarea' },
    { label: "冻结时间", prop: "freezeTime", width: "160", type: "date", editable: true, editType: 'date' },
    { label: "备注", prop: "remark", width: "150", editable: true, editType: 'textarea' }
];

export default column;
